site_name: quantum_sent_emb
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: quantum_sent_emb
      handlers:
        python:
          options:
            docstring_style: numpy